### ISSUE TITLE
Json.toMap() doesn't really return a Map<String, Object>

### ISSUE THREAD

**Issue by LeviticusMB** [nats-io/jparse#13]
```
        Map<String, Object> map = Json.toMap("{ \"key\": \"value\" }");
        System.out.println(map.containsKey("key"));
        System.out.println(map.entrySet().iterator().next().getKey() instanceof String);
        System.out.println(map.get("key"));
```

prints

```
false
false
value
```

and `map.entrySet().iterator().next().getKey().toString()` throws:

```
Exception in thread "main" java.lang.ClassCastException: class io.nats.jparse.node.StringNode cannot be cast to class java.lang.String (io.nats.jparse.node.StringNode is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
```

**Comment by LeviticusMB** [comment]
And also: `map.entrySet().iterator().next().getValue())` throws 

```
Exception in thread "main" java.lang.ClassCastException: class io.nats.jparse.node.StringNode cannot be cast to class io.nats.jparse.node.ObjectNode (io.nats.jparse.node.StringNode and io.nats.jparse.node.ObjectNode are in unnamed module of loader 'app')
	at io.nats.jparse.node.ObjectNode.getObjectNode(ObjectNode.java:239)
	at io.nats.jparse.node.ObjectNode$1$1$1.getValue(ObjectNode.java:129)
	at io.nats.jparse.node.ObjectNode$1$1$1.getValue(ObjectNode.java:121)
```

**Comment by RichardHightower** [comment]
Thank you.

**Comment by RichardHightower** [comment]
See the fix here: 
https://github.com/nats-io/jparse/pull/14

It was meant to be more map-like. 
It should have passed. 
You found a bug. 

ObjectNode is meant to be a java.util.Map<String, Object>
NumberNode is a java.lang.Number 
StringNode is java.lang.CharSequence (which is also what String, StringBuffer, and StringBuilder implement). 
ArrayNode is meant to be java.util.List<Object>.
BooleanNode 
NullNode

It should be somewhat easy to work with just knowing the Java API,. 
There were meant to be no surprises. 

For sure, `map.containsKey("key")` was supposed to work. It does now. 

Thanks for the bug report. 

Please provide feedback to the PR.

**Comment by RichardHightower** [comment]
#13 

```java

        final Map<String, Object> map = Json.toMap("{ \"key\": \"value\"," +
                " \"key1\": 123," +
                " \"key2\": [1,2,3], " +
                " \"key3\": true }"
                );

        assertTrue(map.containsKey("key"));
        assertEquals(map.size(), 4);
        assertFalse(map.isEmpty());

        // Map contains CharSequence as values not strings (which is a StringNode)
        assertTrue(map.get("key") instanceof CharSequence);
        // Map does not have int, long, float, double, etc. but instead java.lang.Number (which is a NumberNode)
        assertTrue(map.get("key1") instanceof Number);
        // JSON arrays are java.util.List and JSON objects are java.util.Map.
        assertTrue(map.get("key2") instanceof List);
        final Set<String> keys = map.keySet();
        assertEquals(new HashSet<>(Arrays.asList("key", "key1", "key2", "key3")),
                keys);
        Collection<Object> values = map.values();
        assertEquals(4, values.size());


        assertEquals("value", map.get("key").toString());
        assertEquals( map.get("key"), "value");
        assertEquals(123, ((Number)map.get("key1")).intValue());
        assertEquals(map.get("key1"), 123);
        assertTrue(((BooleanNode)map.get("key3")).booleanValue());
        assertEquals(map.get("key3"),true );



        //Not all map methods work.
        try {
            map.entrySet().iterator().next();
            fail();
        } catch (UnsupportedOperationException ex) {
            //This map does not support this.
        }

        try {
            map.forEach((s, o) -> {
            });
            fail();
        } catch (UnsupportedOperationException ex) {
            //This map does not support this.
        }
        // Most map methods should work like getOrDefault, computeIfEmpty, computeIfPresent, etc.
```

**Comment by RichardHightower** [comment]
```java
        //See https://github.com/nats-io/jparse/issues/13

        final Map<String, Object> map = Json.toMap("{ \"key\": \"value\"," +
                " \"key1\": 123," +
                " \"key2\": [1,2,3], " +
                " \"key3\": true }"
                );

        assertTrue(map.containsKey("key"));
        assertEquals(map.size(), 4);
        assertFalse(map.isEmpty());

        // Map contains CharSequence as values not strings (which is a StringNode)
        assertTrue(map.get("key") instanceof CharSequence);
        // Map does not have int, long, float, double, etc. but instead java.lang.Number (which is a NumberNode)
        assertTrue(map.get("key1") instanceof Number);
        // JSON arrays are java.util.List and JSON objects are java.util.Map.
        assertTrue(map.get("key2") instanceof List);
        final Set<String> keys = map.keySet();
        assertEquals(new HashSet<>(Arrays.asList("key", "key1", "key2", "key3")),
                keys);
        Collection<Object> values = map.values();
        assertEquals(4, values.size());


        assertEquals("value", map.get("key").toString());
        assertEquals( map.get("key"), "value");
        assertEquals(123, ((Number)map.get("key1")).intValue());
        assertEquals(map.get("key1"), 123);
        assertTrue(((BooleanNode)map.get("key3")).booleanValue());
        assertEquals(map.get("key3"),true );



        //All read map methods should work.
        try {
            String key = map.entrySet().iterator().next().getKey();
            assertTrue(key.startsWith("key"));
        } catch (UnsupportedOperationException ex) {
           fail();
        }

        try {
            map.forEach((s, o) -> {
            });

        } catch (UnsupportedOperationException ex) {
            //This map does not support this.
            fail();
        }
        // Most map methods should work like getOrDefault, computeIfEmpty, computeIfPresent, etc.
```
